name: shapemap-tools
channels:
  - bioconda
  - conda-forge
  - sargueil-citcom
dependencies:
    - cutadapt
    - python=3.9.*
    - fire
    - pandas
    - numpy=1.23
    - matplotlib
    - seaborn=0.12
    - jupyter
    - scikit-bio
    - parse
    - scipy
    - ruamel.yaml
    - voila
    - viennarna
    - varna
    - ipanemap
    - tqdm
    - pip:
        - varnaapi
