name: shapemap-tools
channels:
  - bioconda
  - conda-forge
  - sargueil-citcom
dependencies:
    - cutadapt
    - python=3.9
    - fire
    - pandas
    - numpy=1.26.4
    - matplotlib
    - seaborn=0.12
    - jupyter
    - scikit-bio
    - parse
    - scipy=1.13.1
    - ruamel.yaml
    - jupyter
    - voila
    - viennarna
    - varna
    - ipanemap
    - tqdm
