---
sequence_file: ""
outputdir: ""

conditions:
  default:
    reactivity_file: ''
    alignement_file: ''

format:
  dbn_file_pattern: '{output_dir}/{seqname}-Optimal-{idx}.dbn'
  dbn_centroid_file_pattern: '{output_dir}/centroid/{seqname}-Centroid-{idx}.dbn'

log_file: ""
debug: true

sampling:
  enable: true
  nstructure: 1000
  temperature: 37
  slope: 1.3        # b
  intercept: -0.4   # m

clustering:
  max_diam: 7
  max_avg_diam: 7

pareto:
  percent: 20
  zcutoff: 0.05

visual:
  models: false
  centroids: false
  probing: false


# ipanemap -c [config] -s [sequence]
# --output-dir [outputdir] --log condition --name= --alignement= --shape=
# condition --name --alignemnt --shape sampling --nstructure --temperature
# --slope --intercept clustering --max-diam
