data_folders:
  - demux_fastq/2021-11-23-decrypted-SAMAP-rep0
  - demux_fastq/2022-05-13-decrypted-SAMAP-rep1-1 
  - demux_fastq/2022-06-29-decrypted-SAMAP-rep1-2 
  - demux_fastq/2022-08-10-decrypted-SAMAP-rep3

sequences:
  SAMAP: ../../repos/decrypted/data/1_tagged_sequences/2022-10-27-tagged-aptamer-sequences-natural_artifical_pdb.tsv
  #  RIBOSAM: ../../../decrypted/1_tagged_sequences/2022-10-27-tagged-riboswitch-sam-natural_pdb.tsv
  #  RIBOSAM-PDB: ../../../decrypted/1_tagged_sequences/2022-01-12-tagged-RIBOSAMN-PDB.tsv
  #  SAMAP-PDB: ../../../decrypted/1_tagged_sequences/2022-05-13-tagged-SAMAP-PDB-modified.tsv
shapemapper_output: "results/SAMAP"
shapemapper_output_norm: "results/SAMAP-norm-conds"

parameters:
  - probe
  - sam
  - magnesium
  - temperature

title_template: "{sequence}_{probe}_{sam}SAM_{magnesium}Mg_T{temperature}C_{replicate}"

split_seq: True

samples_file: decrypted-SAMAP_samples.tsv

sequence_config:
  name_col: name
  seq_col: sequence
  prefix_cols: []
  suffix_cols: []
